language: node_js
node_js:
- '0.12'
- '0.11'
branches:
  only:
  - master
before_install:
- env
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip
  chrome.zip
- npm install jspm
- jspm config registries.github.auth $GH_TOKEN
install:
- npm install
script:
- npm start
cache:
  directories:
  - node_modules
  - jspm_packages
notifications:
  email:
  - sysuhuangye@gmail.com
env:
  matrix:
    secure: Cdix+5ms1QheZztMnSp/EFmBTVdxduLtWAa/GvazzKBqn8BLnuDjHYk1UwxI1HqtSO20YO+Tms3KQ0Wfx+6kEFX+XDUl1Lmdrh9RBOe1EQXrC7Ijz1BJ4xH62X3chs/ELPO/cNQgCgYh6b+xtd6mNQrkaTE7r7WyIuNtrTFDN7FxopiVxSt0LIPkEW10uD8YC4LZ9mS6Kbw12qEj1MJjsLC71HPHB11+SjmHoOhfAw+z9oska+HFrHjOcWZMTQ4PieyB+dGCFuGkQ/UgVBT+QKn8XFD90Xc/xfU3pvZw2KjOmv/pRcFPaMnKo81gky9A1CD04hM76aJbPzIUaIXqijAWhFya1qMLifA8zInfq0o8u0/2BfXmqypbq0BxsHdpNFEh72geFnArKcob9vGLcYLhpWr7fAigsGSpZJdhhWlREg7R8D8OORMaXlkiiXpj4k0nZv5H5GlIHqpJEuqJRm90nQfuNaRQkMn+drQCQ2LgkAmDsNbQoJY7oUsVchOaJHjAOVrybvKiZr3z6rIKD3RciqZwIT0BRCbxgJIVMHGiLtvmYdrBuTZ3Ravq49kv1l9mmX5X4BgIhfF9N9RSrOuMnKKWxVXnpfFAXTVyP6d3YVIlP4g5u6ufRJ+LDgZnfTjt+JVXmpCP9YS7I+DKGuNbpWIoy2avApZY7MAKLM8=
