language: node_js
node_js:
- '5.1'
branches:
  only:
  - master
before_install:
- env
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install jspm
- jspm config registries.github.auth $GH_TOKEN
install:
- npm install
- jspm install
script:
- gulp build
cache:
  directories:
  - node_modules
  - jspm_packages
notifications:
  email:
  - sysuhuangye@gmail.com
env:
  matrix:
    secure: Cdix+5ms1QheZztMnSp/EFmBTVdxduLtWAa/GvazzKBqn8BLnuDjHYk1UwxI1HqtSO20YO+Tms3KQ0Wfx+6kEFX+XDUl1Lmdrh9RBOe1EQXrC7Ijz1BJ4xH62X3chs/ELPO/cNQgCgYh6b+xtd6mNQrkaTE7r7WyIuNtrTFDN7FxopiVxSt0LIPkEW10uD8YC4LZ9mS6Kbw12qEj1MJjsLC71HPHB11+SjmHoOhfAw+z9oska+HFrHjOcWZMTQ4PieyB+dGCFuGkQ/UgVBT+QKn8XFD90Xc/xfU3pvZw2KjOmv/pRcFPaMnKo81gky9A1CD04hM76aJbPzIUaIXqijAWhFya1qMLifA8zInfq0o8u0/2BfXmqypbq0BxsHdpNFEh72geFnArKcob9vGLcYLhpWr7fAigsGSpZJdhhWlREg7R8D8OORMaXlkiiXpj4k0nZv5H5GlIHqpJEuqJRm90nQfuNaRQkMn+drQCQ2LgkAmDsNbQoJY7oUsVchOaJHjAOVrybvKiZr3z6rIKD3RciqZwIT0BRCbxgJIVMHGiLtvmYdrBuTZ3Ravq49kv1l9mmX5X4BgIhfF9N9RSrOuMnKKWxVXnpfFAXTVyP6d3YVIlP4g5u6ufRJ+LDgZnfTjt+JVXmpCP9YS7I+DKGuNbpWIoy2avApZY7MAKLM8=
before_deploy:
- cd dist
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: oyupTNTse3/NbNCc7N45MwbnpPgPD/iPdNvFxevK9ymMP7sBoPSJjfYCQKwNmLGvHtjc4zmqYWyBlg472/+OkljVkNqsBFJKRet6Y28Cr/tdNlYN7QrGtM+NvPEATK6z9G2G4Pu1Quj8psiTu0NMmX7s7mRRErkXI/85nZFH9Z3RVnMMKZxd90kinU1NMat4omFQJGsK+/FPMDGzbSq65wyKy+wqx4Oo6aUIO32C/zl8NG7V2WHE1GyX7DpSrCt6x53yD9jEnLpAf7CmERETQaabDFF2a4d89O6vOXLx/ULDOv7M+v3E08JVZEtbp0f0SHQBO87htreiI5ocIaJaD45gWdPuRMFX5zYc8IGTSruLipk+kCTsiZmdXENhEzO6rF7kSlY3vF4j23J/rjqWpnq4N1k85/AOQc7BKrWV8xEaYp//3sdGxRwZDbA6ZBmHeED6jUVZEgmo3LRb0fqnMD4jGRnCBt2/nmAtuYNZawIPckKRYV3mP3lC+f2tforHMLrtPQ7R6ocd2aS4BJGEhcCnyUj/laSE5Vg5CVmi2P+/hp5y0fuqnaUeNUGRnKXjDS5zxAe3JGNDre/J3wGPqcITHeh+YAuqbIHeZx49VpenXrjI6EiJDi5LyGom9IkOJy3SWrSQ7CJk/e1EuOnWK5gZjFFCEYXUcDOFJKQj6ww=
  app: angular-es6
  on:
    repo: crabcanon/angular-es6-demo
