language: node_js
node_js:
- '5.1'
- '4.2'
- '4.1'
branches:
  only:
  - master
before_install:
- env
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install jspm
- jspm config registries.github.auth $GH_TOKEN
install:
- npm install
- jspm install
script:
- gulp build
cache:
  directories:
  - node_modules
  - jspm_packages
notifications:
  email:
  - sysuhuangye@gmail.com
env:
  matrix:
    secure: Cdix+5ms1QheZztMnSp/EFmBTVdxduLtWAa/GvazzKBqn8BLnuDjHYk1UwxI1HqtSO20YO+Tms3KQ0Wfx+6kEFX+XDUl1Lmdrh9RBOe1EQXrC7Ijz1BJ4xH62X3chs/ELPO/cNQgCgYh6b+xtd6mNQrkaTE7r7WyIuNtrTFDN7FxopiVxSt0LIPkEW10uD8YC4LZ9mS6Kbw12qEj1MJjsLC71HPHB11+SjmHoOhfAw+z9oska+HFrHjOcWZMTQ4PieyB+dGCFuGkQ/UgVBT+QKn8XFD90Xc/xfU3pvZw2KjOmv/pRcFPaMnKo81gky9A1CD04hM76aJbPzIUaIXqijAWhFya1qMLifA8zInfq0o8u0/2BfXmqypbq0BxsHdpNFEh72geFnArKcob9vGLcYLhpWr7fAigsGSpZJdhhWlREg7R8D8OORMaXlkiiXpj4k0nZv5H5GlIHqpJEuqJRm90nQfuNaRQkMn+drQCQ2LgkAmDsNbQoJY7oUsVchOaJHjAOVrybvKiZr3z6rIKD3RciqZwIT0BRCbxgJIVMHGiLtvmYdrBuTZ3Ravq49kv1l9mmX5X4BgIhfF9N9RSrOuMnKKWxVXnpfFAXTVyP6d3YVIlP4g5u6ufRJ+LDgZnfTjt+JVXmpCP9YS7I+DKGuNbpWIoy2avApZY7MAKLM8=
before_deploy:
- cd dist
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: o828HeMXV/y6SYzy9M504sb6V7o+kuIyh4wojddryW4G7iivtFhjsQvo/20rOWHQq3xFpbtgRixTZ2FWSLcYlVrxFJDuekWifOAV810Hi27qNZqyHBbdqMKN6unMGnehE0t8mkDH/KDmCzvqTXV/xnaaJsd4Iu8YtpUmXovRC2pFKlBO8siHlN4JsjtDDSlAXg2k1l/cELLom4SDz/22r/UPlS/hkuILRykTTFFn8P8RG8CrMxF4a9z0IqH8amPnjfX5h2UbCFIyytKf7igCWRV5E7jgTB4K8h11sloG9g3ERIOb/V9s/HuUX6PV0n6Tm82BeWdAwkyo5C2JawAtunrz8m8krXv6JinacSTEylZ1lBGYVcO59cz5K7ibUaBEptNY7DK/8bVGn4+j02n/HFyGIsP1J7QzfxZXnzTSeCrUIaUO+O29pr/Nbs/poxPyoswBbvCbtJBu4NlYSKraulpINyIFzBK1l76sg8qb3c3uq1AysFbWSfcd4rkQs2JyjqVS3z75cABG8JyiUXclWrIYLYFMNr5iDoXL1K9iS0SLHheoYfI8d8y0rRL5cpyapd/t9nm4vbpE5Y782B/CVHyicyEnSLQTt2Vqe/nMCIPwYaqFcegGJwiaA79nndO2+tKS3OG6SpF9o+vp7CkoJtvS9TxiEZyRiPK8gkj+JgA=
  app: kiosked-assignment
  on:
    repo: crabcanon/angular-es6-demo
