language: node_js
node_js:
- '5.1'
- '4.2'
- '4.1'
branches:
  only:
  - master
before_install:
- env
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install jspm
- jspm config registries.github.auth $GH_TOKEN
install:
- npm install
- jspm install
script:
- gulp build
cache:
  directories:
  - node_modules
  - jspm_packages
notifications:
  email:
  - sysuhuangye@gmail.com
env:
  matrix:
    secure: Cdix+5ms1QheZztMnSp/EFmBTVdxduLtWAa/GvazzKBqn8BLnuDjHYk1UwxI1HqtSO20YO+Tms3KQ0Wfx+6kEFX+XDUl1Lmdrh9RBOe1EQXrC7Ijz1BJ4xH62X3chs/ELPO/cNQgCgYh6b+xtd6mNQrkaTE7r7WyIuNtrTFDN7FxopiVxSt0LIPkEW10uD8YC4LZ9mS6Kbw12qEj1MJjsLC71HPHB11+SjmHoOhfAw+z9oska+HFrHjOcWZMTQ4PieyB+dGCFuGkQ/UgVBT+QKn8XFD90Xc/xfU3pvZw2KjOmv/pRcFPaMnKo81gky9A1CD04hM76aJbPzIUaIXqijAWhFya1qMLifA8zInfq0o8u0/2BfXmqypbq0BxsHdpNFEh72geFnArKcob9vGLcYLhpWr7fAigsGSpZJdhhWlREg7R8D8OORMaXlkiiXpj4k0nZv5H5GlIHqpJEuqJRm90nQfuNaRQkMn+drQCQ2LgkAmDsNbQoJY7oUsVchOaJHjAOVrybvKiZr3z6rIKD3RciqZwIT0BRCbxgJIVMHGiLtvmYdrBuTZ3Ravq49kv1l9mmX5X4BgIhfF9N9RSrOuMnKKWxVXnpfFAXTVyP6d3YVIlP4g5u6ufRJ+LDgZnfTjt+JVXmpCP9YS7I+DKGuNbpWIoy2avApZY7MAKLM8=
deploy:
  app: kiosked-assignment
  provider: heroku
  api_key:
    secure: gRSTcHNkehk4QCA2DqhAeAIaCAwI3O88M0VnlvlNN0+80V4sVD0T/NC/H/UtaC0+1SRBFkrYpLXwv/ZX4HgDD8MKpdXVmLzeZbXqcjNyMY83hsdFGGxJe/slG3Qxtlux2Td2u2ev5a6WOEx4Nextq5ileB7rLuEGZ+JIIQSdtTQz/8n5K7s/K0jVwGclB9DTM3QIt0ZHAeBngyVgJRDAp4Y2GtllO1fjIeyL/ZxHlZw25RjwGzi4ovOi74JGisCAPeJ51Sds52KAn+L/EOaWGtEeuY67E0cRwMb4AbQAbxrfvfDw7F+oWbn2FR7ySDSADX3US36T9rJ/TDa03qDsyvqvuDHK73nwLXnT6K4YcimzlRXs8GAoTVqqfp1EiRtXq7wuPk6PmZCjjhS4WpY38MgqI0Cmazd4IHH0YQzWUOHZfi32pnhURMpv5tZrr7c8h0vsbTGlcmYEX4pxhfazE2TJPRn8Y8HtN91B0W7itNVaamP/o2UzsCSFnB9vmhgJE4HR3jca2IWykVyZYvaKr60GiNwzzY7jHXHqNc3EJ6STZLAMJMyYbRhJCnf8n4FCouvwwvY383wrBYvHXNeCgLtqUepenxzoMP8Ay5k2GLwG7MfBc4BMXLi2F7VRiB5TdWLUkq+9oQlH/ehjjgZedEUUC+yTG+8AuGQZOnareAM=
